# Makefile: BasicBoss Cross Compiler
# datum: 28.12.2009
#
# Befehl zum erstellen des bbcompiler:
# make


bbcompiler: bbcompiler.c boss_abbild.inc
	gcc -Wall -O3 -s -o bbcompiler bbcompiler.c

